### ISSUE TITLE
Update creator tool does not enforce expected format of 'bug_fixes' field in update-descriptor.yaml

### ISSUE THREAD

**Issue by uvindra** [wso2/update-creator-tool#27]
**Description:**
If the update-descriptor.yaml has a 'bug_fixes' entry beginning with a number as follows

```yaml
update_number: xxx
platform_version: xxxx
platform_name: xxxx
applies_to: xxxxx
bug_fixes:
  1623: Some Title
description: |
  Some description
file_changes:
  added_files: []
  removed_files: []
  modified_files: []
```
It does not complain of an error an creates the wum update. However the wum-update server complains with the following error,

_wum: unable to generate update request Reason: Formatting issue in 'bug_fixes' field of update_descriptor.yaml_ 

This issue does not arise when you add the complete github URL such as,

```yaml
update_number: xxx
platform_version: xxxx
platform_name: xxxx
applies_to: xxxxx
bug_fixes:
  https://github.com/xxxx/xxxxx/issues/1623: Some Title
description: |
  Some description
file_changes:
  added_files: []
  removed_files: []
  modified_files: []
```

Ideally the update tool should validate this to make sure that the 'bug_fixes' does not begin with a number

**Suggested Labels:**
Bug
